### ISSUE TITLE
cannot find package

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [sensorario/go-tris#5]
If I try to build the project I get this error:

```
game.go:6:2: cannot find package "github.com/sensorario/bashutil" in any of:
	/usr/local/go/src/github.com/sensorario/bashutil (from $GOROOT)
	($GOPATH not set)
```

**Comment by sensorario** [comment]
You need to get sensorario/bashutil package. Run the following statement:

    go get sensorario/bashutil

You need to be shure that your working directory is right and yoi binaries, packages and source code are in the right folder. Thisi is my $GOPATH

    /Users/sensorario/work

Here you can find $GOPATH/src with source codes. in $GOPATH/pck all the packages installed (without main package) and finally in $GOPATH/bin all the build (packages with main package)

**Comment by AlessandroMinoccheri** [comment]
Perfect! Now It works fine
